In [4]:
import pandas as pd

df = pd.read_csv(r"C:\Users\saksh\Desktop\Retail-Sales-Forecasting\data\raw\walmart.csv")

df.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

In [5]:
import numpy as np

df['Simulated_Demand'] = df['Weekly_Sales'] + np.random.normal(0, 5000, len(df))

df[['Weekly_Sales', 'Simulated_Demand']].head()

   Weekly_Sales  Simulated_Demand
0    1643690.90      1.648269e+06
1    1641957.44      1.645805e+06
2    1611968.17      1.598411e+06
3    1409727.59      1.402557e+06
4    1554806.68      1.554834e+06

In [7]:
# Step 1: Date ko datetime me convert karo
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

# Step 2: Month extract karo
df['Month'] = df['Date'].dt.month

# Step 3: Seasonality apply karo
df['Seasonality'] = df['Month'].apply(lambda x: 1.2 if x in [11,12] else 0.9)

# Step 4: Seasonal sales calculate karo
df['Seasonal_Sales'] = df['Weekly_Sales'] * df['Seasonality']

# Output check
df[['Date','Month','Weekly_Sales','Seasonal_Sales']].head()

        Date  Month  Weekly_Sales  Seasonal_Sales
0 2010-02-05      2    1643690.90     1479321.810
1 2010-02-12      2    1641957.44     1477761.696
2 2010-02-19      2    1611968.17     1450771.353
3 2010-02-26      2    1409727.59     1268754.831
4 2010-03-05      3    1554806.68     1399326.012

In [8]:
# Initial stock define
initial_stock = 1000000

# Stock level calculate (cumulative sales minus)
df['Stock_Level'] = initial_stock - df['Weekly_Sales'].cumsum()

# Output check
df[['Date','Weekly_Sales','Stock_Level']].head()

        Date  Weekly_Sales  Stock_Level
0 2010-02-05    1643690.90   -643690.90
1 2010-02-12    1641957.44  -2285648.34
2 2010-02-19    1611968.17  -3897616.51
3 2010-02-26    1409727.59  -5307344.10
4 2010-03-05    1554806.68  -6862150.78

In [9]:
# Initial stock define
initial_stock = 20000000

# Stock level calculate (cumulative sales minus)
df['Stock_Level'] = initial_stock - df['Weekly_Sales'].cumsum()

# Output check
df[['Date','Weekly_Sales','Stock_Level']].head()

        Date  Weekly_Sales  Stock_Level
0 2010-02-05    1643690.90  18356309.10
1 2010-02-12    1641957.44  16714351.66
2 2010-02-19    1611968.17  15102383.49
3 2010-02-26    1409727.59  13692655.90
4 2010-03-05    1554806.68  12137849.22

In [10]:
# Stock-out condition
df['Stock_Out'] = df['Stock_Level'] < 0

# Check results
df[['Date','Stock_Level','Stock_Out']].head()

        Date  Stock_Level  Stock_Out
0 2010-02-05  18356309.10      False
1 2010-02-12  16714351.66      False
2 2010-02-19  15102383.49      False
3 2010-02-26  13692655.90      False
4 2010-03-05  12137849.22      False

In [11]:
# Reorder point (example logic)
reorder_point = df['Weekly_Sales'].mean() * 2

# Reorder decision
df['Reorder'] = df['Stock_Level'] < reorder_point

# Output check
df[['Date','Stock_Level','Reorder']].head()

        Date  Stock_Level  Reorder
0 2010-02-05  18356309.10    False
1 2010-02-12  16714351.66    False
2 2010-02-19  15102383.49    False
3 2010-02-26  13692655.90    False
4 2010-03-05  12137849.22    False